### ISSUE TITLE
Is this abandonned?

### ISSUE THREAD

**Issue by phaazon** [the-real-blackh/libvorbis#2]
Hi,

I’d like to know whether this project is discontinued. If so, I can relay.

**Comment by the-real-blackh** [comment]
Do you want to take it over?

**Comment by phaazon** [comment]
Well, I’m using it, it works, but it won’t be able to fit in stackage, and I get update it. :)

**Comment by the-real-blackh** [comment]
Would you like to fix it?

**Comment by phaazon** [comment]
I may push some changes from time to time, yeah.

**Comment by the-real-blackh** [comment]
I gave you commit privilege just in case.

**Comment by phaazon** [comment]
Thanks! :)
